# Generated by Django 2.2.4 on 2019-09-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('create_new_blog_post', 'Can create new blog post')]},
        ),
    ]
