# Generated by Django 2.2.4 on 2019-09-04 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190904_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
